# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


main_a = Analysis(
    ['main.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

main_pyz = PYZ(main_a.pure, main_a.zipped_data, cipher=block_cipher)

main_exe = EXE(
    main_pyz,
    main_a.scripts,
    main_a.binaries,
    main_a.zipfiles,
    main_a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

settings_a = Analysis(
    ['settings.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

settings_pyz = PYZ(settings_a.pure, settings_a.zipped_data, cipher=block_cipher)

settings_exe = EXE(
    settings_pyz,
    settings_a.scripts,
    settings_a.binaries,
    settings_a.zipfiles,
    settings_a.datas,
    [],
    exclude_binaries=True,
    name='settings',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Test36_a = Analysis(
    ['Tasks36.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
Test36_pyz = PYZ(Test36_a.pure, Test36_a.zipped_data, cipher=block_cipher)

Test36_exe = EXE(
    Test36_pyz,
    Test36_a.scripts,
    Test36_a.binaries,
    Test36_a.zipfiles,
    Test36_a.datas,
    [],
    exclude_binaries=True,
    name='Test36',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Test46_a = Analysis(
    ['Tasks46.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
Test46_pyz = PYZ(Test46_a.pure, Test46_a.zipped_data, cipher=block_cipher)

Test46_exe = EXE(
    Test46_pyz,
    Test46_a.scripts,
    Test46_a.binaries,
    Test46_a.zipfiles,
    Test46_a.datas,
    [],
    exclude_binaries=True,
    name='Test46',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Test56_a = Analysis(
    ['Tasks56.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
Test56_pyz = PYZ(Test56_a.pure, Test56_a.zipped_data, cipher=block_cipher)

Test56_exe = EXE(
    Test56_pyz,
    Test56_a.scripts,
    Test56_a.binaries,
    Test56_a.zipfiles,
    Test56_a.datas,
    [],
    exclude_binaries=True,
    name='Test56',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Test67_a = Analysis(
    ['Tasks67.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
Test67_pyz = PYZ(Test67_a.pure, Test67_a.zipped_data, cipher=block_cipher)

Test67_exe = EXE(
    Test67_pyz,
    Test67_a.scripts,
    Test67_a.binaries,
    Test67_a.zipfiles,
    Test67_a.datas,
    [],
    exclude_binaries=True,
    name='Test67',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Tests_a = Analysis(
    ['Tests.py'],
    pathex=['C:\\Users\\Harkoner\\PycharmProjects\\pythonProject\\Tasks'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
Tests_pyz = PYZ(Tests_a.pure, Tests_a.zipped_data, cipher=block_cipher)

Tests_exe = EXE(
    Tests_pyz,
    Tests_a.scripts,
    Tests_a.binaries,
    Tests_a.zipfiles,
    Tests_a.datas,
    [],
    exclude_binaries=True,
    name='Tests',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    main_exe,
    main_a.binaries,
    main_a.zipfiles,
    main_a.datas,
    settings_exe,
    settings_a.binaries,
    settings_a.zipfiles,
    settings_a.datas,
    Test36_exe,
    Test36_a.binaries,
    Test36_a.zipfiles,
    Test36_a.datas,
    Test46_exe,
    Test46_a.binaries,
    Test46_a.zipfiles,
    Test46_a.datas,
    Test56_exe,
    Test56_a.binaries,
    Test56_a.zipfiles,
    Test56_a.datas,
    Test67_exe,
    Test67_a.binaries,
    Test67_a.zipfiles,
    Test67_a.datas,
    Tests_exe,
    Tests_a.binaries,
    Tests_a.zipfiles,
    Tests_a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Main_program',
)